name: Build DGL from Source

on:
  workflow_dispatch:
    inputs:
      build-type:
        type: string
        description: 'Build type (Release/Debug)'
        required: true
        default: ''
        options: 
        - 'release'
        - 'dev'
        - 'dogfood'
      platform-type:
        type: choice
        description: 'Build type (CPU/GPU)'
        required: true
        default: 'CPU'
        options: 
        - 'CPU'
        - 'GPU'
      cuda-version:
        type: string
        description: 'CUDA version (GPU build only)'
        required: false
        default: '12.8'
      extra_args:
        type: string
        description: 'Extra build arguments'
        required: false
        default: ''


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev make cmake

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Create conda environment
      run: |
        sudo apt-get install -y wget
        wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH
        source $HOME/miniconda/bin/activate
        if [ "${{ github.event.inputs.platform-type }}" == "GPU" ]; then
          bash script/create_dev_conda_env.sh -s -g 12.4 -n dgl-dev
        else
          bash script/create_dev_conda_env.sh -s -c -n dgl-dev
        fi

    - name: Build shared library
      run: |
        source $HOME/miniconda/bin/activate dgl-dev
        mkdir -p build
        cd build
        if [ "${{ github.event.inputs.platform-type }}" == "GPU" ]; then
          cmake -DBUILD_TYPE=${{ github.event.inputs.build-type }} -DUSE_CUDA=OFF ${{ github.event.inputs.extra_args }} ..
        else
          cmake -DBUILD_TYPE=${{ github.event.inputs.build-type }} -DUSE_CUDA=ON ${{ github.event.inputs.extra_args }} ..
        fi
        make -j$(nproc)

    - name: Install wheel package
      run: |
        source $HOME/miniconda/bin/activate dgl-dev
        pip install wheel

    - name: Build wheel
      working-directory: ./python
      run: |
        source $HOME/miniconda/bin/activate dgl-dev
        python setup.py bdist_wheel

    - name: Upload wheel as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dgl-wheel
        path: ./python/dist/*.whl
